#!/bin/bash -e
echo "Welcome to:"
echo "-----------"
echo "         __   __     __            __   __       ___  __   __"
echo " |\/| | /__\` /__\` | /  \\ |\\ |     /  \` /  \\ |\\ |  |  |__) /  \\ |"
echo " |  | | .__/ .__/ | \\__/ | \\| ___ \\__, \\__/ | \\|  |  |  \\ \\__/ |___"
echo -e "\n\nInstallation is progress...\n"
sudo apt-get -q update
sudo apt-get -y install build-essential ruby2.3 ruby2.3-dev
echo "Installing: bundler"
sudo gem install bundler --no-ri --no-rdoc
bundle install
ruby=`which ruby`
sudo $ruby scripts/menu_main.rb
